export const GET_MOVIE = 'GET_MOVIE'
export const SET_MOVIE_DANG_CHIEU = 'SET_MOVIE_DANG_CHIEU'
export const SET_MOVIE_SAP_CHIEU = 'SET_MOVIE_SAP_CHIEU'
export const SET_THONG_TIN_PHIM = 'SET_THONG_TIN_PHIM'